# Generated by Django 3.0.6 on 2020-05-08 09:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(
                    default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.CharField(max_length=64)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(
                    default=uuid.uuid4, editable=False, unique=True)),
                ('flight', models.CharField(max_length=64)),
                ('reserved', models.DateTimeField(blank=True, null=True)),
                ('ticket_class', models.PositiveSmallIntegerField(choices=[
                 (0, 'Passenger'), (1, 'Business'), (2, 'First class')], default=0)),
                ('flight_time', models.DateTimeField(blank=True, null=True)),
                ('row', models.PositiveSmallIntegerField()),
                ('column', models.PositiveSmallIntegerField()),
                ('passenger_ref', models.CharField(
                    blank=True, max_length=64, null=True)),
                ('passenger_name', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('checked_in', models.DateTimeField(blank=True, null=True)),
                ('sale', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticketing.Sale')),
            ],
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer'],
                               name='ticketing_s_custome_a1aae2_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(
                fields=['flight', 'passenger_ref'], name='ticketing_t_flight_127a12_idx'),
        ),
    ]
